### ISSUE TITLE
does not support "@apollo/datasource-rest": "^6.0.0"

### ISSUE THREAD

**Issue by samuelseaton** [kimyvgy/worker-apollo-server-template#36]
attempted to upgrade the @apollo/datasource-rest package to latest (6.0.0), but receive this error:

<img width="484" alt="image" src="https://github.com/kimyvgy/worker-apollo-server-template/assets/47338733/7fb0e3f7-2a23-46d5-bb59-b42c117084f0">

**Comment by kimyvgy** [comment]
The PR #51 solved this issue
