### ISSUE TITLE
Disabling playground

### ISSUE THREAD

**Issue by simplenotezy** [kimyvgy/worker-apollo-server-template#56]
How do you disable the playground?

**Comment by kimyvgy** [comment]
@simplenotezy There is a built-in plugin called Landing Page. You can customize the landing page with the following document:
https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/.

In summary:
- The default landing page for [non-production environments](https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/#default-non-production-landing-page) (ApolloServerPluginLandingPageLocalDefault)
- The default landing page for [production](https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/#default-production-landing-page) (ApolloServerPluginLandingPageProductionDefault)
- Using [GraphQL Playground](https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/#graphql-playground-landing-page) as a landing page (ApolloServerPluginLandingPageGraphQLPlayground)
- [Disabling the landing page entirely](https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/#disabling-the-landing-page)

https://github.com/kimyvgy/worker-apollo-server-template/blob/d82ac948d8ee4cfa8e0d8e4461de65a6ec03081c/src/index.ts#L12

**Comment by simplenotezy** [comment]
Thanks for the indepth answer @kimyvgy !

**Comment by simplenotezy** [comment]
@kimyvgy How would you disable it in production? I could enable it via `.dev.vars` but since the `const server = ...` is defined outside of where we can fetch the env context, what can we do?

```ts
const server = new ApolloServer<Context>({
  typeDefs,
  resolvers,
  introspection: process.env.ENVIRONMENT === 'development', // this won't work
  plugins: [
    ApolloServerPluginLandingPageProductionDefault({
      footer: false, //
    }),
  ],
});
```
