### ISSUE TITLE
Worker types

### ISSUE THREAD

**Issue by harnonlabs** [kimyvgy/worker-apollo-server-template#8]
Any ideas why this should be happening?

<img width="732" alt="image" src="https://user-images.githubusercontent.com/59741803/202584946-b5d0f68a-96ef-43e4-8e56-e816533bc7f1.png">

**Comment by kimyvgy** [comment]
@harnonlabs I think it is a bug in Miniflare. Let me check it.

**Comment by kimyvgy** [comment]
@harnonlabs It seems the error appears in the latest version of Miniflare & Wrangler.

Currently, I frozen Miniflare at v2.9.0 and Wrangler at v2.1.9 to avoid the error (8907902). I will investigate more about the error when I have free time.

Please try again with the latest code. Let me know if the error still occurs.

**Comment by harnonlabs** [comment]
Thanks for taking a look @kimyvgy. Indeed it looks like an error with undici package. Let's see how this unfolds...
